### ISSUE TITLE
有季度的选择器吗

### ISSUE THREAD

**Issue by XUGAOBO** [nickeljew/react-month-picker#1]

**Comment by nickeljew** [comment]
如果你不需要选季度间的时间段（即 第一季度 到 第三季度），而只是单选某个季度的话，可以用我另外那个 React-Picker 组件来满足需求，唯一缺点就是年份范围的计算要自己另外处理，也不难。

如果确实需要时间段的选择，这个暂时没有。

**Comment by XUGAOBO** [comment]
好的,谢谢,我自己在修改下
