### ISSUE TITLE
Feature request: Allow to specify min and max month-year

### ISSUE THREAD

**Issue by rpiaggio** [nickeljew/react-month-picker#11]
If min or max is specified, the months previous to min or after max would appear as disabled (as is already done automatically in range mode).

Thank you!

**Comment by nickeljew** [comment]
Auto-disabling of year-buttons was fixed in v1.0.13. Disabling style is available in v1.0.14

**Comment by RoarkeRandall** [comment]
So if I want only Oct 2016 and earlier selectable it's not possible? This is kind of a deal breaker for me, any plans for this feature?

**Comment by nickeljew** [comment]
I will cover this feature in a week, if you can wait. @RoarkeRandall

**Comment by nickeljew** [comment]
@RoarkeRandall Please check v1.1.2.
