### ISSUE TITLE
Module not found: Error: Can't resolve 'month-picker'

### ISSUE THREAD

**Issue by FerPerales** [nickeljew/react-month-picker#12]
Hello!

I'm trying to use the month picker but I got this error:

`Module not found: Error: Can't resolve 'month-picker'`

Installing via `npm install`

The relevant part of my package.json:

```
"react-month-picker": "1.1.2",
```

Trying to use in my component as follows:

`import Picker from 'month-picker'`

More info:

`react 15.1.0`
`node 7.2.1`
`npm 4.0.3`

Any idea on what's going on?

Thanks in advance

**Comment by nickeljew** [comment]
import Picker from 'react-month-picker'

**Comment by FerPerales** [comment]
@nickeljew thanks :D
