### ISSUE TITLE
How to close date picker on selection

### ISSUE THREAD

**Issue by jofomah** [nickeljew/react-month-picker#17]
Hi, 

after selecting month and year, can the picker just close automatically?

**Comment by nickeljew** [comment]
By default, when you can close it by clicking on the outside area of the month picker.
Moreover, you also can implement onChange handler to call MonthPicker::dismiss() to close it when value is changed.

**Comment by jofomah** [comment]
@nickeljew thanks

**Comment by ShekharSahu** [comment]
@nickeljew  could you please elaborate more on how do we call this MonthPicker::dismiss() from outside this component.
