### ISSUE TITLE
样式引入不进去

### ISSUE THREAD

**Issue by XUGAOBO** [nickeljew/react-month-picker#2]

**Comment by nickeljew** [comment]
直接import CSS的话不合适，因为 import CSS在浏览器端会触发一次下载请求，但是组件的 css 并不在你的项目资源目录下。所以要直接使用 CSS 文件的话，请自行从组件目录下复制 CSS 文件到项目的资源目录。

如果使用 SCSS 文件的话，由于目前 SCSS 还没有成熟的包管理机制，所以暂时只能自行直接 import 组件目录下的 SCSS 文件（例如 @import "../node_modules/react-month-picker/scss/month-picker"; ）。或者也可以自行把 SCSS 文件复制到项目目录。

**Comment by XUGAOBO** [comment]
![Uploading 1.png…]()

![Uploading 3.png…]()

**Comment by XUGAOBO** [comment]
1、 将css样式拷贝到xxx.css文件中
2、import styles from './xxx.css';
3、<div className={styles["edit"]}></div>

**Comment by XUGAOBO** [comment]
3、<div className={styles["edit"]}>

**Comment by XUGAOBO** [comment]
div className={styles["edit"]}

**Comment by nickeljew** [comment]
我不是很明白你做了什么。如果直接使用 CSS 文件，要么把文件 month-picker.css 文件复制到你的项目的 css 目录里，要么直接把 month-picker.css 的内容复制到你的 css 文件里去。

如果是复制内容，那就不需要 import 了。你明白 import 的意义不？

至于你的第三步，我没看懂

**Comment by XUGAOBO** [comment]
额,我也不是很明白,但是我们项目一直都是这样引入css样式的,我想截图,为啥老是传不上去

**Comment by nickeljew** [comment]
查了下，你们用的是 CSS Modules 库来管理 CSS 的。React-Month-Picker 不支持也不是采用 CSS Modules 的规则写的 CSS，所以你无法引入。我个人并不喜欢 CSS Modules 这种技术思想，所以无法给你提供支持。
