### ISSUE TITLE
prop-types version

### ISSUE THREAD

**Issue by dariuszsobkowicz** [nickeljew/react-month-picker#28]
can't install package, `prop-types` version `16.6.0` not exist

`"peerDependencies": {
    "prop-types": "^16.6.0",
    "react": "^16.0.0",
    "react-dom": "^16.0.0"
  },`

**Comment by nickeljew** [comment]
sorry about my carelessness, and already fixed and updated

**Comment by dariuszsobkowicz** [comment]
ty @nickeljew

**Comment by dariuszsobkowicz** [comment]
would you update `react-tapper` to support react 16?

**Comment by nickeljew** [comment]
yup, just did

**Comment by dariuszsobkowicz** [comment]
ty @nickeljew 😀
