### ISSUE TITLE
Is value required?

### ISSUE THREAD

**Issue by nmaves** [nickeljew/react-month-picker#31]
It does not appear to be required via the prop-types but if I don't provide one it fails at runtime.

**Comment by nickeljew** [comment]
Yes, there is a minor bug here. 

However, it’s not feasible to set it as required, coz both of prop value and prop range are valid “value” input.

I will fix this after Chinese New Year holiday. Please set an input value as empty string for now.

**Comment by nickeljew** [comment]
although it was a very old issue, but eventually it was just fixed recently with updated version react proptypes.
