### ISSUE TITLE
@Types Creation?

### ISSUE THREAD

**Issue by granticusmaximus** [nickeljew/react-month-picker#32]
Is there a possibility for the creation of a full @type list?

**Comment by granticusmaximus** [comment]
Similar to those found [here](https://github.com/DefinitelyTyped/DefinitelyTyped)

**Comment by granticusmaximus** [comment]
Any time that I npm start on the app utilizing the reac-month-picker, it is stating that the @types/react-month-picker are required, and before I try to dive in and create them, ( i am an extremely new devloper) I wanted to see if you would have any format of creating them

**Comment by granticusmaximus** [comment]
[This](https://www.npmjs.com/~types) is the list that I found from NPM that has all the @types. And I am not sure how to create declaration files for this module. I am using the demo version of this module: 

`DocReady(function () {

        class MonthBox extends Component {
            constructor(props: any, context: any) {
                super(props, context)

                this.state = {
                    value: this.props.value || 'N/A',
                }

                this._handleClick = this._handleClick.bind(this)
            }

            componentWillReceiveProps(nextProps) {
                this.setState({
                    value: nextProps.value || 'N/A',
                })
            }

            render() {

                return (
                    <div className="box" onClick={this._handleClick}>
                        <label>{this.state.value}</label>
                    </div>
                )
            }

            _handleClick(e) {
                this.props.onClick && this.props.onClick(e)
            }
        }

        MonthBox.propTypes = {
            value: PropTypes.string,
            onClick: PropTypes.func,
        }

        class List extends Component {
            constructor(props, context) {
                super(props, context)

                this.state = {
                    mrange: { from: { year: 2017, month: 8 }, to: { year: 2019, month: 5 } },
                }

                this._handleClickRangeBox = this._handleClickRangeBox.bind(this)
                this.handleRangeChange = this.handleRangeChange.bind(this)
                this.handleRangeDissmis = this.handleRangeDissmis.bind(this)

            }

            componentWillReceiveProps(nextProps) {
                this.setState({
                    value: nextProps.value || 'N/A',
                })
            }

            render() {

                const pickerLang = {
                    months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                    from: 'From', to: 'To',
                }
                const mrange = this.state.mrange

                const makeText = m => {
                    if (m && m.year && m.month) return (pickerLang.months[m.month - 1] + '. ' + m.year)
                    return '?'
                }

                return (
                    <ul id="MonthBox">
                        <li>
                            <label><b>Pick A Span of Months</b><span>(Available years from 2017 to this year)</span></label>
                            <div className="edit">
                                <Picker
                                    ref="pickRange"
                                    years={{ min: 2017 }}
                                    range={mrange}
                                    lang={pickerLang}
                                    theme="light"
                                    onChange={this.handleRangeChange}
                                    onDismiss={this.handleRangeDissmis}
                                >
                                    <MonthBox value={makeText(mrange.from) + ' ~ ' + makeText(mrange.to)} onClick={this._handleClickRangeBox} />
                                </Picker>
                            </div>
                        </li>
                    </ul>
                )
            }

            handleClickMonthBox(e) {
                this.refs.pickAMonth.show()
            }
            handleAMonthChange(value, text) {
                //
            }
            handleAMonthDissmis(value) {
                this.setState({ mvalue: value })
            }

            handleClickMonthBox2(e) {
                this.refs.pickAMonth2.show()
            }
            handleAMonthChange2(value, text) {
                //
            }
            handleAMonthDissmis2(value) {
                this.setState({ mvalue2: value })
            }

            _handleClickRangeBox(e) {
                this.refs.pickRange.show()
            }
            handleRangeChange(value, text, listIndex) {
                //
            }
            handleRangeDissmis(value) {
                this.setState({ mrange: value })
            }

            _handleClickRangeBox2(e) {
                this.refs.pickRange2.show()
            }
            handleRangeChange2(value, text, listIndex) {
                //
            }
            handleRangeDissmis2(value) {
                this.setState({ mrange2: value })
            }
        }







        class Main extends Component {
            constructor(props, context) {
                super(props, context)

                this.state = {
                    value: this.props.value
                }
            }

            componentWillReceiveProps(nextProps) {
                this.setState({
                    value: nextProps.value
                })
            }

            render() {

                return (
                    <div className="list-area">
                        <List />
                    </div>
                )
            }
        }


        Main.propTypes = {
            value: PropTypes.string,
            onClick: PropTypes.func,
        }





        ReactDOM.render(
            <Main />,
            Dom.nodeById("page-container"))


    })`

So I am just not sure where to begin with that creation. Guidance would be awesome

**Comment by nickeljew** [comment]
“the creation of a full @type list”

I’m not sure what you are referring to?

**Comment by nickeljew** [comment]
I think those @types/* packages are converted from original version into TypeScript version by contributors. I’m not one of those contributors in that project.

If you are going to do it, please post your request to the owner of that project.

**Comment by granticusmaximus** [comment]
Who is the owner?

**Comment by nickeljew** [comment]
Sorry, that's not my project, and I have no responsibility for offering TypeScript version of react-month-picker to be listed in @types project.

**Comment by granticusmaximus** [comment]
Okay thanks
