### ISSUE TITLE
Change month manually

### ISSUE THREAD

**Issue by sarates** [nickeljew/react-month-picker#34]
Is this is possible to change month manually ( next / prev month) ? Need to reduce the number of clicks for user (change month without dropdown)

**Comment by nickeljew** [comment]
You meant using keyboard?

**Comment by sarates** [comment]
Nope, something like this:

![screenshot_11](https://user-images.githubusercontent.com/4117293/36743050-ee60e646-1bf1-11e8-8813-2b42b8a0bce2.png)

**Comment by nickeljew** [comment]
That’s your job actually.
The component does not include the displaying box for the selected month
also.
It’s your job to decide and build how to show a displaying box, a button or
something else with extra operations.
To be honest, if you don’t need the dropdown, this component is useless
to you.
