### ISSUE TITLE
multi select support

### ISSUE THREAD

**Issue by rezof** [nickeljew/react-month-picker#46]
i have a use case where i need multiple months selection.
would you be interested in adding such feature ? i can create a PR if you're interested.

**Comment by nickeljew** [comment]
Could you tell me more about this scenario with multiple month selection?

**Comment by rezof** [comment]
something like this: (it's from a jquery/bootstrap widget)
<img width="218" alt="Screen Shot 2019-08-21 at 12 54 31" src="https://user-images.githubusercontent.com/15073300/63429763-df84f980-c412-11e9-90e4-0717f5053954.png">

**Comment by SurfinSpirit** [comment]
Also interested in this feature.

**Comment by nickeljew** [comment]
multiple selection is released in v2.1.1
