### ISSUE TITLE
componentWillReceiveProps deprecation

### ISSUE THREAD

**Issue by panuhorsmalahti** [nickeljew/react-month-picker#47]
This component uses `componentWillReceiveProps` on https://github.com/nickeljew/react-month-picker/blob/master/src/month-picker.jsx#L206. Using this component causes a warning to be printed (due to https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html).

The component should be migrated away from this lifecycle method.

I wonder if `getDerivedStateFromProps` could work instead?

**Comment by ckruse** [comment]
has been fixed with #50
