### ISSUE TITLE
React 0.15 compatibility? 

### ISSUE THREAD

**Issue by egmanoj** [nickeljew/react-month-picker#5]
Trying to install, got the following error:

```
npm ERR! Linux 3.19.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "react-month-picker" "--save"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.0.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@15.0.2 wants react@^15.0.2
npm ERR! peerinvalid Peer react-redux@4.4.5 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer react-month-picker@1.0.8 wants react@^0.14.3
```

Is there any plan to move to React 0.15+? 

Thanks.

**Comment by nickeljew** [comment]
Please read this:
http://stackoverflow.com/questions/35890730/react-15-not-compatible-with-react-redux
"Note that you can use npm@3.x which doesn’t enforce peer dependencies. This way, you don’t have to wait for project authors to update their packages."

React was set as a peer dependency for this component, and npm@2.x will enforce version of your local package in node_modules folder to match, but it's unnecessary.

React 15 is very new, I will test it in few days.

Now that you are using the latest React, why not upgrade your Node and NPM to the latest, or at least to v5.x.x.

**Comment by egmanoj** [comment]
@nickeljew Thanks, I'll give that a shot and see.
