### ISSUE TITLE
Failed Build React App

### ISSUE THREAD

**Issue by lfoliveir4** [nickeljew/react-month-picker#55]
When executing my project with the "yarn start" command, after adding any react library, the library reports the following warning and the project does not execute:

![image](https://user-images.githubusercontent.com/32423942/79401602-ee9b5780-7f5f-11ea-8ef1-7404798758c3.png)

The previous solution for this issue is to comment all lines in the month-picker.scss file that contains "@include". Would this problem have a definitive solution?

**Comment by nickeljew** [comment]
please try v2.1.1. I just removed all mixins defined in bourbon library
