### ISSUE TITLE
Warnings with react@15.2.1

### ISSUE THREAD

**Issue by thiagoc7** [nickeljew/react-month-picker#7]
Hi, thanks for this awesome picker, it's working very well!
I just have this warning:

![image](https://cloud.githubusercontent.com/assets/6671184/17249465/7be0f536-5576-11e6-8e79-dfd95648a6b3.png)

**Comment by nickeljew** [comment]
Could you show your codes using MonthPicker and tell me which version of react you are using?

**Comment by thiagoc7** [comment]
sure, `react 15.2.1`

```javascript
import React, {Component, PropTypes} from 'react';
import Picker from 'react-month-picker'

class MonthPicker extends Component {
  onChange(year, month) {
    this.refs.picker.dismiss();
    window.location = `/?date=${year}-${month}-01`
  }

  render() {
    const { year, month, date } = this.props;
    return (
    <Picker
        ref="picker"
        years={{min: year - 3, max: year + 2}}
        value={{year, month}}
        lang={['Jan', 'Feb', 'Mar', 'Spr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']}
        onChange={this.onChange.bind(this)}
    >
      <h1 className="page-title pointer" onClick={() => this.refs.picker.show()}>{date}</h1>
    </Picker>
    );
  }
}

MonthPicker.propTypes = {
  year: PropTypes.number.isRequired,
  month: PropTypes.number.isRequired,
  date: PropTypes.string.isRequired
};

export default MonthPicker;
```

**Comment by severisv** [comment]
I am also getting this warning with react-month-picker 1.0.11 and React 15.3.0

**Comment by nickeljew** [comment]
It's fixed, and thanks for the help from @jmeline

**Comment by 823844596** [comment]
@nickeljew , how do you solve this issue? i met the same problem by use react-month-picker 1.0.11 and react 15.3.0 . do i need to update the version?  thank you!

**Comment by nickeljew** [comment]
@823844596 yes, new version of the react-month-picker (1.0.12) solved the issue. Actually, the issue was caused by react-tapper.

**Comment by 823844596** [comment]
@nickeljew  ok, thank you for your help!
