### ISSUE TITLE
Incrementing Year Doesn't Work

### ISSUE THREAD

**Issue by ryan4888** [nickeljew/react-month-picker#8]
When clicking the increment year button ">" it simply doesn't do anything. The decrement "<" works as expected. 

When I click the increment button it disappears from the right side of the calendar, and jumps over to the left side, and appears on top of the decrement button. No errors occur. 

Looks like "goNextYear" isn't being called. "goPrevYear" works fine though. Any idea what the cause of this could be?

**Comment by nickeljew** [comment]
Could you provide more info about that?
such as: Which version of react? on desktop or mobile device? Did you check console? Is there any error message? Or, can you show your code?
I can't figure out any cause for now, since it works fine in my example page.

**Comment by ryan4888** [comment]
React v15.0.2. Happens on Chrome, Firefox, and Safari. I checked console, and no error messages appeared. I have since removed the code. It was VERY basic though. Essentially following the example.

**Comment by nickeljew** [comment]
This issued was fixed in v1.0.13. Please check it.
